# 1. Write a python program to display all the header tags from wikipedia.org.

In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

def header_tags(link):
    html = urlopen(link)
    bs = BeautifulSoup(html, "html.parser")
    titles = bs.find_all(['h1', 'h2','h3','h4','h5','h6'])
    print(*titles, sep='\n\n')

header_tags(link="https://en.wikipedia.org/wiki/Main_Page")

<h1 class="firstHeading mw-first-heading" id="firstHeading" style="display: none"><span class="mw-page-title-main">Main Page</span></h1>

<h1><span class="mw-headline" id="Welcome_to_Wikipedia">Welcome to <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a></span></h1>

<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>

<h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>

<h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>

<h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>

<h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>

<h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>

<h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>

<h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>

<h2>Navigation menu</h2>

<h3 class="vector-menu-heading" id="p-personal-label">
<span class="vector-menu-heading-label">Personal tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-namespaces-label">
<span class="vector-menu-heading-label">Namespaces</span>
</h3>

<h3 class="vector-menu-heading" id="p-views-label">
<span class="vector-menu-heading-label">Views</span>
</h3>

<h3>
<label for="searchInput">Search</label>
</h3>

<h3 class="vector-menu-heading" id="p-navigation-label">
<span class="vector-menu-heading-label">Navigation</span>
</h3>

<h3 class="vector-menu-heading" id="p-interaction-label">
<span class="vector-menu-heading-label">Contribute</span>
</h3>

<h3 class="vector-menu-heading" id="p-tb-label">
<span class="vector-menu-heading-label">Tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-coll-print_export-label">
<span class="vector-menu-heading-label">Print/export</span>
</h3>

<h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
<span class="vector-menu-heading-label">In other projects</span>
</h3>

<h3 class="vector-menu-heading" id="p-lang-label">
<span class="vector-menu-heading-label">Languages</span>
</h3>

# 2. Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame.

In [40]:
import requests
import pandas as pd
import re

def imdb_top_100(url="https://www.imdb.com/chart/top/"):
    web_page = requests.get(url)
    web_page.content
    soup = BeautifulSoup(web_page.content, "html.parser")
    soup.prettify
    
    # Finding Movie Names
    movie_names = soup.find_all('td', class_="titleColumn")
    movies = []
    for movie in movie_names:
        movie = movie.get_text().replace("\n", "")
        movies.append(movie.strip(" "))
        
    #Movie Ratings
    all_ratings = soup.find_all('td', class_="ratingColumn imdbRating")
    ratings = []
    for rating in all_ratings:
        rating = rating.get_text().replace("\n", "")
        ratings.append(rating)
        
    # Creating data frame and extracting name, year, number
    df = pd.DataFrame()
    df['movies'] = movies
    df['ratings'] = ratings

    # Removing additional Spaces
    new_movies = []
    for i in df["movies"]:
        a = i.replace("      ", "")
        new_movies.append(a)
    # print(len(new_movies))

    # Adding New Data Frame to DF

    df["new"] = new_movies
    
    
    # Seperating Releasing Year
    release_year = []
    for i in range(0, len(df)):
        a_string = df["movies"][i]
        result = re.search(r"\(([A-Za-z0-9_]+)\)", a_string)
        release_year.append(result.group(1))
    # print(release_year)


    
    # Adding releasing year to DF
    df["Release Year"] = release_year  # Seperating release year
    df.head()
    
    
    # Deleting Existing Name from Data Frame
    # New_Movie_name added in file
    bc = []
    for i in range(0, len(df["new"])):
        in_str = str(i)
        len_of_st = len(in_str) + 1
        a = df["new"][i][len_of_st:-6]
        bc.append(a)
    df["Movie Name"] = bc
    
    
    new_df = pd.DataFrame()
    new_df.style.hide_index()
    new_df["Rank"] = [i for i in range(1, 251)]
    new_df["Movie Name"] = bc
    new_df["Year"] = release_year
    new_df["Ratings"] = ratings
    return new_df.head(100)


imdb_top_100()

C:\Users\shiva\AppData\Local\Temp\ipykernel_20724\1926710735.py:69: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  new_df.style.hide_index()

    Rank                         Movie Name  Year Ratings
0      1           The Shawshank Redemption  1994     9.2
1      2                      The Godfather  1972     9.2
2      3                    The Dark Knight  2008     9.0
3      4              The Godfather Part II  1974     9.0
4      5                       12 Angry Men  1957     8.9
..   ...                                ...   ...     ...
95    96                       Citizen Kane  1941     8.3
96    97  M - Eine Stadt sucht einen Mörder  1931     8.3
97    98                 North by Northwest  1959     8.3
98    99                       Idi i smotri  1985     8.2
99   100                           .Vertigo  1958     8.2

[100 rows x 4 columns]

# Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year of release) and make data frame.

In [41]:
imdb_top_100(url="https://www.imdb.com/india/top-rated-indian-movies/")

C:\Users\shiva\AppData\Local\Temp\ipykernel_20724\1926710735.py:69: FutureWarning: this method is deprecated in favour of `Styler.hide(axis='index')`
  new_df.style.hide_index()

    Rank                   Movie Name  Year Ratings
0      1   Rocketry: The Nambi Effect  2022     8.5
1      2                   Anbe Sivam  2003     8.4
2      3                     Jai Bhim  2021     8.4
3      4                      Golmaal  1979     8.4
4      5                      Nayakan  1987     8.4
..   ...                          ...   ...     ...
95    96   The Legend of Bhagat Singh  2002     8.0
96    97                    Virumandi  2004     8.0
97    98  Baahubali 2: The Conclusion  2017     8.0
98    99                       Angoor  1982     8.0
99   100             .Rang De Basanti  2006     8.0

[100 rows x 4 columns]

# Write s python program to display list of respected former presidents of India(i.e. Name , Term of office)
## From https://presidentofindia.nic.in/former-presidents.htm

In [8]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [11]:
def presidents_info(url):
    page = requests.get(url)
    page.content
    soup = BeautifulSoup(page.content, "html.parser")
    soup.prettify
    president_name = soup.find_all('ul', class_="listing cf")

    lis = []
    new_list = []
    for ul in president_name:
        for li in ul.findAll('li'):
            if li.find('ul'):
                break
            lis.append(li)

        for li in lis:
            # print(li.text.encode("utf-8"))
            new_list.append(li.text.encode("utf-8"))
    # Extracting Names
    presidents = []
    for i in range(0, len(new_list)):
        a = str(new_list[i]).replace("\\n", "")
        leb_ = a.find("(")
        # print(a[2:leb_])
        presidents.append(a[2:leb_])
    # print(presidents)
    
    year = []
    for i in range(0, len(new_list)):
        a = str(new_list[i]).replace("\\n", "")
        start_ = a.find("(")
        end_ = a.find(")")
        # print(a[start_:end_])
        year.append(a[start_+1:end_])
    # print(year)
    df = pd.DataFrame()
    df["Presidents"] = presidents
    df["Serving Year"] = year
    print(df)
url = "https://presidentofindia.nic.in/former-presidents.htm" 

presidents_info(url)

                       Presidents  Serving Year
0           Shri Ram Nath Kovind   birth - 1945
1          Shri Pranab Mukherjee      1935-2020
2   Smt Pratibha Devisingh Patil   birth - 1934
3         DR. A.P.J. Abdul Kalam      1931-2015
4           Shri K. R. Narayanan    1920 - 2005
5        Dr Shankar Dayal Sharma      1918-1999
6            Shri R Venkataraman      1910-2009
7               Giani Zail Singh      1916-1994
8      Shri Neelam Sanjiva Reddy      1913-1996
9       Dr. Fakhruddin Ali Ahmed      1905-1977
10  Shri Varahagiri Venkata Giri      1894-1980
11              Dr. Zakir Husain      1897-1969
12  Dr. Sarvepalli Radhakrishnan      1888-1975
13           Dr. Rajendra Prasad      1884-1963